In [1]:
! pip install finance-datareader

In [2]:
import FinanceDataReader as fdr
from tqdm import tqdm

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
import os
import itertools
import random

from sklearn.preprocessing import MinMaxScaler, StandardScaler

import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import Dense,  GRU, Concatenate, Dropout, LSTM, SimpleRNN, TimeDistributed, Bidirectional
from tensorflow.keras import Sequential, Input, Model, layers, optimizers
from tensorflow.keras.optimizers import SGD, Adam

In [3]:
random.seed(1234)
np.random.seed(1234)
os.environ["PYTHONHASHSEED"] = str(1234)
tf.random.set_seed(1234)

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [23]:
path = '/content/drive/MyDrive/주식 종가 예측/open/'
list_name = 'stock_list.csv'
stock_list = pd.read_csv(os.path.join(path,list_name))
stock_list['종목코드'] = stock_list['종목코드'].apply(lambda x : str(x).zfill(6))
stock_list

종목명    종목코드    상장시장
0        삼성전자  005930   KOSPI
1      SK하이닉스  000660   KOSPI
2       NAVER  035420   KOSPI
3         카카오  035720   KOSPI
4    삼성바이오로직스  207940   KOSPI
..        ...     ...     ...
365      맘스터치  220630  KOSDAQ
366        다날  064260  KOSDAQ
367   제이시스메디칼  287410  KOSDAQ
368   크리스에프앤씨  110790  KOSDAQ
369     쎄트렉아이  099320  KOSDAQ

[370 rows x 3 columns]

# Public

In [24]:
start_date = '20210104'
end_date = '20211105'

start_weekday = pd.to_datetime(start_date).weekday()
max_weeknum = pd.to_datetime(end_date).strftime('%V')
business_days = pd.DataFrame(pd.date_range(start_date,end_date,freq='B'), columns = ['Date'])

In [12]:
def RNN_model(X_train, y_train, X_val, y_val):

  model = Sequential()
  model.add(SimpleRNN(units = 1, input_shape = (X_train.shape[1], 1), activation = 'tanh', return_sequences = True))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))

  model.add(TimeDistributed(Dense(units = 1)))

  model.compile(optimizer = Adam(learning_rate = 0.01), loss = 'mean_absolute_error', metrics=['mae']) 

  es = EarlyStopping(monitor ='val_loss', mode ='min', verbose = 1, patience = 10)
  model_save_folder_path = '/content/drive/MyDrive/주식 종가 예측/RNN3/'
  model_path = model_save_folder_path + f'{code}.h5'
  mc = ModelCheckpoint(model_path, monitor ='val_loss', mode ='min', verbose = 1, save_best_only = True)

  model.fit(X_train, y_train, epochs = 100, batch_size = 2, verbose = 1, shuffle = False, callbacks = [es, mc],
                      validation_data=(X_val, y_val))

  return model

In [13]:
submission_name = 'sample_submission.csv'
submission = pd.read_csv(os.path.join(path,submission_name))

In [14]:
nmae_df = pd.DataFrame(columns = ['code', 'nmae'])

In [15]:
import warnings
warnings.filterwarnings("ignore")

for code in tqdm(stock_list['종목코드'].values):
  tf.random.set_seed(1234)
  
  # 해당 종목의 데이터 가져온 후 주 단위 데이터로 나타내기
  stock_price = fdr.DataReader(code, start = start_date, end = end_date)[['Close']].reset_index()
  stock_price = pd.merge(business_days, stock_price, how = 'outer')
  stock_price['weekday'] = stock_price.Date.apply(lambda x : x.weekday())
  stock_price['weeknum'] = stock_price.Date.apply(lambda x : x.strftime('%V'))
  stock_price.Close = stock_price.Close.ffill()
  stock_price = pd.pivot_table(data = stock_price, values = 'Close', columns = 'weekday', index = 'weeknum')

  X_train = stock_price.iloc[0:-12].to_numpy()
  X_val = stock_price.iloc[-12:-2].to_numpy()
  X_test = stock_price.iloc[-2].to_numpy()

  y_train = stock_price.iloc[1:-11].to_numpy()
  y_val = stock_price.iloc[-11:-1].to_numpy()
  y_test = stock_price.iloc[-1].to_numpy()

  # 스케일링 시행
  scaler = MinMaxScaler()

  X_train_scaled = scaler.fit_transform(X_train.reshape(-1, 1)).reshape(32, 5)
  X_val_scaled = scaler.fit_transform(X_val.reshape(-1, 1)).reshape(10, 5)
  X_test_scaled = scaler.fit_transform(X_test.reshape(-1, 1)).reshape(1, 5)

  y_train_scaled = scaler.fit_transform(y_train.reshape(-1, 1)).reshape(32, 5)
  y_val_scaled = scaler.fit_transform(y_val.reshape(-1, 1)).reshape(10, 5)
  y_test_scaled = scaler.fit_transform(y_test.reshape(-1, 1)).reshape(1, 5)

  X_train_scaled = np.reshape(X_train_scaled, (X_train_scaled.shape[0], X_train_scaled.shape[1]))
  X_val_scaled = np.reshape(X_val_scaled, (X_val_scaled.shape[0], X_val_scaled.shape[1]))
  X_test_scaled = np.reshape(X_test_scaled, (X_test_scaled.shape[0], X_test_scaled.shape[1]))
  
  # 모델 학습
  model = RNN_model(X_train_scaled, y_train_scaled, X_val_scaled, y_val_scaled)
  model = keras.models.load_model(f"/content/drive/MyDrive/주식 종가 예측/RNN3/{code}.h5")

  # 예측
  y_pred = model.predict(X_test_scaled)
  y_pred = y_pred.reshape(1,5)
  y_pred = scaler.inverse_transform(y_pred)

  nmae = np.mean(np.abs(y_test - y_pred) / y_test)

  nmae_df = nmae_df.append({'code' : code, 'nmae' : nmae}, ignore_index = True)
  
  print(y_pred)
  print(nmae)
    
  for i in range (0, 5):
    submission.loc[i, code] = y_pred[0][i]

Output hidden; open in https://colab.research.google.com to view.

In [16]:
# nmae 평균
nmae_result = np.array(nmae_df['nmae'])

In [17]:
np.mean(nmae_result)

0.01729472269182923

# Private

In [18]:
start_date = '20210104'
end_date = '20211126'

start_weekday = pd.to_datetime(start_date).weekday()
max_weeknum = pd.to_datetime(end_date).strftime('%V')
business_days = pd.DataFrame(pd.date_range(start_date,end_date,freq='B'), columns = ['Date'])

In [19]:
for code in tqdm(stock_list['종목코드'].values):
  
  # 해당 종목의 데이터 가져온 후 주 단위 데이터로 나타내기
  stock_price = fdr.DataReader(code, start = start_date, end = end_date)[['Close']].reset_index()
  stock_price = pd.merge(business_days, stock_price, how = 'outer')
  stock_price['weekday'] = stock_price.Date.apply(lambda x : x.weekday())
  stock_price['weeknum'] = stock_price.Date.apply(lambda x : x.strftime('%V'))
  stock_price.Close = stock_price.Close.ffill()
  stock_price = pd.pivot_table(data = stock_price, values = 'Close', columns = 'weekday', index = 'weeknum')

  X_test = stock_price.iloc[46].to_numpy()

  # 스케일링 시행
  scaler = MinMaxScaler()

  X_test_scaled = scaler.fit_transform(X_test.reshape(-1, 1)).reshape(1, 5)
  X_test_scaled = np.reshape(X_test_scaled, (X_test_scaled.shape[0], X_test_scaled.shape[1]))
  
  # 모델 학습
  model = keras.models.load_model(f"/content/drive/MyDrive/주식 종가 예측/RNN3/{code}.h5")

  # 예측
  y_pred = model.predict(X_test_scaled)
  y_pred = y_pred.reshape(1,5)
  y_pred = scaler.inverse_transform(y_pred)

  print(y_pred)
    
  for i in range (0, 5):
    submission.loc[i + 5, code] = y_pred[0][i] # 임시로 채워주기 위한 용도. 최종 예측 시에는 바꿔주어야 함!

  0%|          | 1/370 [00:03<18:32,  3.02s/it]

[[74066.81  74212.29  74222.57  74172.62  74012.945]]


  1%|          | 2/370 [00:05<18:00,  2.94s/it]

[[117885.28  118416.055 118179.734 118151.42  118114.96 ]]


  1%|          | 3/370 [00:08<17:28,  2.86s/it]

[[404254.44 403072.88 398436.53 395858.03 394789.5 ]]


  1%|          | 4/370 [00:11<17:16,  2.83s/it]

[[127876.22  125808.11  124964.02  127495.375 126201.18 ]]


  1%|▏         | 5/370 [00:14<16:36,  2.73s/it]

[[866250.75 858869.06 856517.1  853805.56 862785.3 ]]


  2%|▏         | 6/370 [00:16<16:40,  2.75s/it]

[[68209.24 68123.13 68114.29 67864.63 67805.12]]


  2%|▏         | 7/370 [00:19<17:32,  2.90s/it]

[[746641.1  745337.9  740964.6  742051.2  739634.75]]


  2%|▏         | 8/370 [00:23<18:35,  3.08s/it]

[[737709.4 739449.1 732427.8 721703.6 721103.8]]


  2%|▏         | 9/370 [00:26<18:26,  3.07s/it]

[[212418.84 211812.14 216086.   211021.28 211596.12]]


  3%|▎         | 10/370 [00:29<17:55,  2.99s/it]

[[218534.94 215787.81 215693.11 212919.03 216314.67]]


  3%|▎         | 11/370 [00:32<18:03,  3.02s/it]

[[83658.47  83588.805 83073.31  83493.6   83566.805]]


  3%|▎         | 12/370 [00:35<17:42,  2.97s/it]

[[280419.3  281558.75 281217.03 280805.72 280370.66]]


  4%|▎         | 13/370 [00:38<17:54,  3.01s/it]

[[128150.36 128616.03 128621.38 127411.44 125173.14]]


  4%|▍         | 14/370 [00:41<17:17,  2.91s/it]

[[114065.01 114738.39 114798.45 114162.48 113834.48]]


  4%|▍         | 15/370 [00:44<18:34,  3.14s/it]

[[242876.7  241604.23 241244.34 239369.05 237160.73]]


  4%|▍         | 16/370 [00:47<18:22,  3.11s/it]

[[214136.8  214067.39 214043.27 214046.86 213730.11]]


  5%|▍         | 17/370 [00:50<18:15,  3.10s/it]

[[1155825.1 1157502.6 1155403.6 1157259.6 1169295.5]]


  5%|▍         | 18/370 [00:53<17:55,  3.06s/it]

[[309500.6  309500.5  309500.53 309500.62 309500.53]]


  5%|▌         | 19/370 [00:56<17:26,  2.98s/it]

[[56375.934 56937.406 57251.695 57309.492 56360.312]]


  5%|▌         | 20/370 [00:59<17:36,  3.02s/it]

[[37234.06  37230.28  37364.176 37271.504 37336.906]]


  6%|▌         | 21/370 [01:02<16:58,  2.92s/it]

[[249491.66 248359.83 249564.95 254124.75 255417.22]]


  6%|▌         | 22/370 [01:05<17:51,  3.08s/it]

[[725152.3  720214.44 712898.7  701073.6  703152.6 ]]


  6%|▌         | 23/370 [01:08<17:33,  3.04s/it]

[[25415.648 25412.443 25419.19  25432.05  25440.719]]


  6%|▋         | 24/370 [01:11<17:15,  2.99s/it]

[[22236.15  22295.846 22295.03  22304.922 22263.887]]


  7%|▋         | 25/370 [01:14<16:40,  2.90s/it]

[[65418.617 65569.695 65725.52  65647.31  65418.7  ]]


  7%|▋         | 26/370 [01:17<16:19,  2.85s/it]

[[154138.58 154220.73 154481.77 154114.9  153698.28]]


  7%|▋         | 27/370 [01:19<16:16,  2.85s/it]

[[174267.27 174183.89 174230.7  174519.69 174349.36]]


  8%|▊         | 28/370 [01:22<16:10,  2.84s/it]

[[176613.55 176808.39 176195.69 175489.62 172643.19]]


  8%|▊         | 29/370 [01:26<17:01,  3.00s/it]

[[42732.977 42598.18  42874.633 42762.08  42395.88 ]]


  8%|▊         | 30/370 [01:28<16:14,  2.87s/it]

[[122307.81  122293.37  122351.336 122364.18  122472.47 ]]


  8%|▊         | 31/370 [01:31<16:17,  2.88s/it]

[[154281.12 152478.2  151825.27 151607.9  152305.  ]]


  9%|▊         | 32/370 [01:33<15:11,  2.70s/it]

[[388548.88 390835.88 390531.78 390002.88 383009.22]]


  9%|▉         | 33/370 [01:36<15:25,  2.75s/it]

[[23316.432 23433.213 23434.262 23486.498 23319.967]]


  9%|▉         | 34/370 [01:39<15:42,  2.80s/it]

[[87053.17 87587.25 88511.41 88456.21 87579.82]]


  9%|▉         | 35/370 [01:42<16:14,  2.91s/it]

[[84370.4  84271.98 84299.74 84299.5  84280.55]]


 10%|▉         | 36/370 [01:45<15:59,  2.87s/it]

[[28294.057 28173.363 28082.465 28417.297 27833.16 ]]


 10%|█         | 37/370 [01:48<16:35,  2.99s/it]

[[214257.25 214033.84 214548.62 214199.14 214300.67]]


 10%|█         | 38/370 [01:51<16:16,  2.94s/it]

[[489275.75 497552.12 499834.78 502514.38 502117.97]]


 11%|█         | 39/370 [01:54<16:17,  2.95s/it]

[[96927.3   97189.625 97089.1   97025.42  95624.805]]


 11%|█         | 40/370 [01:56<14:59,  2.73s/it]

[[100485.3   100341.46   98942.945  98322.     99322.91 ]]


 11%|█         | 41/370 [01:59<15:07,  2.76s/it]

[[209314.17 209908.97 209471.97 209298.48 209083.81]]


 11%|█▏        | 42/370 [02:02<15:16,  2.79s/it]

[[30973.14  30945.207 30946.654 31007.604 31063.688]]


 12%|█▏        | 43/370 [02:05<15:42,  2.88s/it]

[[13574.474 13584.209 13571.797 13576.104 13515.961]]


 12%|█▏        | 44/370 [02:08<16:21,  3.01s/it]

[[21901.572 21945.826 21937.53  21721.213 21516.406]]


 12%|█▏        | 45/370 [02:11<15:42,  2.90s/it]

[[13339.927 13386.528 13385.667 13386.995 13365.847]]


 12%|█▏        | 46/370 [02:14<15:35,  2.89s/it]

[[35478.777 35676.98  35348.816 34927.387 34249.027]]


 13%|█▎        | 47/370 [02:17<16:14,  3.02s/it]

[[11080.312 11061.063 11222.267 11256.954 11106.911]]


 13%|█▎        | 48/370 [02:20<15:48,  2.95s/it]

[[157805.97 158891.88 159078.97 158924.1  158632.9 ]]


 13%|█▎        | 49/370 [02:23<15:39,  2.93s/it]

[[40434.99  40420.43  40369.58  40324.066 40341.344]]


 14%|█▎        | 50/370 [02:26<15:22,  2.88s/it]

[[370197.6  367353.8  368224.16 369721.4  370453.1 ]]


 14%|█▍        | 51/370 [02:29<15:22,  2.89s/it]

[[13819.586 13832.071 13880.052 13835.44  13851.651]]


 14%|█▍        | 52/370 [02:32<15:57,  3.01s/it]

[[162492.86 162653.67 162406.23 162233.52 159995.47]]


 14%|█▍        | 53/370 [02:35<15:34,  2.95s/it]

[[74560.01 74309.54 74241.19 73986.09 74252.06]]


 15%|█▍        | 54/370 [02:38<16:00,  3.04s/it]

[[47531.324 47635.613 47671.418 47839.79  47753.234]]


 15%|█▍        | 55/370 [02:41<15:20,  2.92s/it]

[[40495.83  40669.766 40577.387 40529.543 40092.07 ]]


 15%|█▌        | 56/370 [02:44<15:31,  2.97s/it]

[[9106.081 9105.126 9110.099 9106.792 9112.237]]


 15%|█▌        | 57/370 [02:47<15:15,  2.93s/it]

[[24603.957 24584.61  24556.225 24417.129 24081.865]]


 16%|█▌        | 58/370 [02:49<14:59,  2.88s/it]

[[83839.41  83779.305 83537.28  83455.375 83474.29 ]]


 16%|█▌        | 59/370 [02:52<14:58,  2.89s/it]

[[56344.844 56083.203 56030.965 55879.562 56762.684]]


 16%|█▌        | 60/370 [02:55<14:46,  2.86s/it]

[[286389.   283867.97 285571.94 289392.03 289154.1 ]]


 16%|█▋        | 61/370 [02:58<14:41,  2.85s/it]

[[55168.902 55216.168 54833.77  54497.96  54324.312]]


 17%|█▋        | 62/370 [03:01<14:48,  2.89s/it]

[[46045.78  45923.38  45772.67  45264.49  44740.766]]


 17%|█▋        | 63/370 [03:04<14:42,  2.87s/it]

[[22747.375 22835.877 22901.488 22894.186 22901.053]]


 17%|█▋        | 64/370 [03:06<14:15,  2.79s/it]

[[157022.02 156993.23 157001.27 156786.2  155985.33]]


 18%|█▊        | 65/370 [03:09<13:56,  2.74s/it]

[[105722.375 107107.51  106994.67  106267.695 105199.78 ]]


 18%|█▊        | 66/370 [03:12<14:09,  2.80s/it]

[[38806.348 38837.664 38522.895 38747.34  38219.75 ]]


 18%|█▊        | 67/370 [03:14<13:46,  2.73s/it]

[[53177.83  53198.812 53684.71  53737.617 53918.26 ]]


 18%|█▊        | 68/370 [03:18<14:36,  2.90s/it]

[[59822.273 59638.965 59638.71  59559.836 59597.68 ]]


 19%|█▊        | 69/370 [03:21<14:33,  2.90s/it]

[[39369.17  39298.168 39253.39  39390.375 39430.652]]


 19%|█▉        | 70/370 [03:23<14:26,  2.89s/it]

[[135004.34 135938.14 135631.16 134449.95 131934.05]]


 19%|█▉        | 71/370 [03:26<14:15,  2.86s/it]

[[39846.977 40081.39  40221.305 40153.133 39683.953]]


 19%|█▉        | 72/370 [03:29<14:26,  2.91s/it]

[[7842.243  7810.6616 7788.0806 7820.5073 7756.8457]]


 20%|█▉        | 73/370 [03:32<14:10,  2.86s/it]

[[33895.094 33900.668 33907.164 33960.59  33841.96 ]]


 20%|██        | 74/370 [03:35<14:54,  3.02s/it]

[[5480.912  5493.6855 5490.452  5486.2603 5389.75  ]]


 20%|██        | 75/370 [03:38<14:33,  2.96s/it]

[[31849.074 31894.488 31815.531 31734.566 31362.07 ]]


 21%|██        | 76/370 [03:41<14:38,  2.99s/it]

[[55042.918 55304.027 55309.38  55270.137 55217.09 ]]


 21%|██        | 77/370 [03:44<14:17,  2.93s/it]

[[47188.652 47016.535 47165.836 47078.23  47159.668]]


 21%|██        | 78/370 [03:47<13:51,  2.85s/it]

[[266778.25 266348.25 266991.53 266734.06 266804.72]]


 21%|██▏       | 79/370 [03:50<13:48,  2.85s/it]

[[100488.82  101442.24  101469.57  101066.64  100417.734]]


 22%|██▏       | 80/370 [03:52<13:23,  2.77s/it]

[[532485.1  536716.25 534903.4  530882.2  517320.9 ]]


 22%|██▏       | 81/370 [03:56<14:18,  2.97s/it]

[[39770.152 39605.54  39598.754 39423.7   39050.902]]


 22%|██▏       | 82/370 [03:58<14:02,  2.93s/it]

[[128456.68 128005.81 129627.24 133475.95 134773.86]]


 22%|██▏       | 83/370 [04:01<13:34,  2.84s/it]

[[31875.504 32032.81  32020.703 31786.326 31387.115]]


 23%|██▎       | 84/370 [04:04<13:29,  2.83s/it]

[[77436.69  77245.055 77126.555 76915.19  76060.03 ]]


 23%|██▎       | 85/370 [04:07<13:28,  2.84s/it]

[[13016.253 13019.387 13015.126 13002.839 12962.629]]


 23%|██▎       | 86/370 [04:09<13:05,  2.77s/it]

[[60226.773 60402.258 60266.832 59817.055 59540.85 ]]


 24%|██▎       | 87/370 [04:12<13:09,  2.79s/it]

[[25745.197 25735.309 24859.58  25083.213 24689.08 ]]


 24%|██▍       | 88/370 [04:15<13:08,  2.80s/it]

[[113591.875 113771.83  113617.47  113488.28  112617.85 ]]


 24%|██▍       | 89/370 [04:18<13:14,  2.83s/it]

[[229269.16 227921.88 227989.31 228484.33 228999.36]]


 24%|██▍       | 90/370 [04:21<13:29,  2.89s/it]

[[5121.513 5119.404 5141.306 5143.637 5128.356]]


 25%|██▍       | 91/370 [04:24<13:21,  2.87s/it]

[[41796.332 42509.62  39375.797 35056.14  34666.734]]


 25%|██▍       | 92/370 [04:27<13:27,  2.90s/it]

[[74359.22  73227.92  73835.81  73761.555 75271.31 ]]


 25%|██▌       | 93/370 [04:30<13:19,  2.89s/it]

[[37663.773 37968.18  38076.344 38128.42  37960.53 ]]


 25%|██▌       | 94/370 [04:33<13:46,  2.99s/it]

[[20356.533 20345.088 20300.068 20403.09  20364.777]]


 26%|██▌       | 95/370 [04:36<13:52,  3.03s/it]

[[30382.076 30344.242 30270.783 30088.012 30178.223]]


 26%|██▌       | 96/370 [04:39<13:36,  2.98s/it]

[[34585.29  35314.72  35668.953 35529.496 35414.266]]


 26%|██▌       | 97/370 [04:41<12:36,  2.77s/it]

[[50134.934 50294.38  50249.562 50135.32  49812.68 ]]


 26%|██▋       | 98/370 [04:44<12:39,  2.79s/it]

[[36981.438 37095.934 36984.258 36959.613 36910.99 ]]


 27%|██▋       | 99/370 [04:46<11:48,  2.61s/it]

[[15732.026 15785.79  15675.187 15654.992 15616.508]]


 27%|██▋       | 100/370 [04:49<11:56,  2.65s/it]

[[96099.086 96517.93  95869.19  95607.79  95662.32 ]]


 27%|██▋       | 101/370 [04:52<12:01,  2.68s/it]

[[106974.95 106461.25 105554.5  105423.41 104115.21]]


 28%|██▊       | 102/370 [04:55<12:17,  2.75s/it]

[[5910.0244 5913.8105 5910.2935 5908.4    5899.0034]]


 28%|██▊       | 103/370 [04:58<13:04,  2.94s/it]

[[77006.414 77031.82  77358.03  76969.67  78245.44 ]]


 28%|██▊       | 104/370 [05:01<12:58,  2.93s/it]

[[34080.62  33889.285 34185.594 33859.93  33861.168]]


 28%|██▊       | 105/370 [05:04<12:51,  2.91s/it]

[[114712.734 114692.625 114852.99  114135.87  113493.96 ]]


 29%|██▊       | 106/370 [05:06<12:28,  2.83s/it]

[[3248.9617 3261.8591 3260.0803 3256.1094 3225.289 ]]


 29%|██▉       | 107/370 [05:09<12:25,  2.83s/it]

[[316663.28 315156.62 316812.4  315967.56 313265.44]]


 29%|██▉       | 108/370 [05:12<12:22,  2.83s/it]

[[302728.47 302068.22 303306.34 301307.2  304910.3 ]]


 29%|██▉       | 109/370 [05:15<12:17,  2.83s/it]

[[356012.12 359561.97 359653.   357944.8  355821.34]]


 30%|██▉       | 110/370 [05:18<13:00,  3.00s/it]

[[29696.865 29541.377 30274.096 30746.893 30904.555]]


 30%|███       | 111/370 [05:21<12:14,  2.83s/it]

[[146860.81 146771.44 145995.42 147346.92 147469.2 ]]


 30%|███       | 112/370 [05:23<12:06,  2.82s/it]

[[60221.89  60715.625 60743.48  60574.15  60219.504]]


 31%|███       | 113/370 [05:26<12:03,  2.81s/it]

[[23461.436 23444.576 23474.568 23439.395 23632.996]]


 31%|███       | 114/370 [05:29<12:04,  2.83s/it]

[[151639.34 151812.   151932.6  151668.38 151087.2 ]]


 31%|███       | 115/370 [05:32<12:04,  2.84s/it]

[[86686.76  87669.266 89085.13  89876.02  89113.9  ]]


 31%|███▏      | 116/370 [05:35<12:03,  2.85s/it]

[[75016.38  74759.625 75251.55  75188.734 75024.75 ]]


 32%|███▏      | 117/370 [05:38<12:07,  2.87s/it]

[[637873.75 648398.6  651011.75 641275.3  638516.3 ]]


 32%|███▏      | 118/370 [05:41<12:29,  2.98s/it]

[[229368.45 230829.38 229281.47 227147.11 223171.25]]


 32%|███▏      | 119/370 [05:44<12:01,  2.87s/it]

[[20592.822 20674.316 20773.922 20757.852 20885.795]]


 32%|███▏      | 120/370 [05:46<11:52,  2.85s/it]

[[97779.97  98043.49  98156.555 97932.41  98265.6  ]]


 33%|███▎      | 121/370 [05:49<11:41,  2.82s/it]

[[77489.52 77174.24 78302.26 78120.14 77895.3 ]]


 33%|███▎      | 122/370 [05:52<11:38,  2.82s/it]

[[77436.03  77501.305 77426.23  77449.68  77410.76 ]]


 33%|███▎      | 123/370 [05:55<11:37,  2.83s/it]

[[43679.605 43758.125 43777.727 43924.11  43709.312]]


 34%|███▎      | 124/370 [05:58<11:38,  2.84s/it]

[[96833.43  96998.586 97053.92  97100.25  97172.76 ]]


 34%|███▍      | 125/370 [06:01<12:08,  2.98s/it]

[[8604.383 8646.644 8742.286 8749.779 8660.678]]


 34%|███▍      | 126/370 [06:04<11:56,  2.94s/it]

[[102998.39  102996.555 102994.375 102993.14  102993.04 ]]


 34%|███▍      | 127/370 [06:06<11:32,  2.85s/it]

[[32711.8   32830.824 32679.455 32245.004 31706.47 ]]


 35%|███▍      | 128/370 [06:10<11:51,  2.94s/it]

[[55042.45  55028.04  54994.543 54827.867 54694.285]]


 35%|███▍      | 129/370 [06:12<11:42,  2.91s/it]

[[24982.264 25295.365 25552.223 25352.139 24896.309]]


 35%|███▌      | 130/370 [06:15<11:30,  2.88s/it]

[[32260.965 32259.484 32207.219 32069.312 31625.41 ]]


 35%|███▌      | 131/370 [06:18<11:40,  2.93s/it]

[[1903.6903 1902.6044 1902.7136 1900.1859 1886.6711]]


 36%|███▌      | 132/370 [06:21<11:30,  2.90s/it]

[[2189.8118 2191.258  2200.7532 2217.516  2256.836 ]]


 36%|███▌      | 133/370 [06:24<11:09,  2.82s/it]

[[77301.73 77428.52 77735.52 77123.68 76054.16]]


 36%|███▌      | 134/370 [06:27<11:19,  2.88s/it]

[[44039.68 43934.68 44087.44 44043.68 44158.97]]


 36%|███▋      | 135/370 [06:30<11:13,  2.87s/it]

[[39507.21  39645.73  39562.426 39540.582 39543.86 ]]


 37%|███▋      | 136/370 [06:32<11:09,  2.86s/it]

[[30317.223 30350.926 30430.117 30461.828 30609.447]]


 37%|███▋      | 137/370 [06:35<11:00,  2.84s/it]

[[93163.42 92835.5  91202.03 93454.01 92053.65]]


 37%|███▋      | 138/370 [06:38<11:02,  2.86s/it]

[[26170.166 25395.291 25538.965 26072.098 26794.076]]


 38%|███▊      | 139/370 [06:41<11:09,  2.90s/it]

[[23066.559 23147.736 23196.85  23148.451 22937.254]]


 38%|███▊      | 140/370 [06:44<11:04,  2.89s/it]

[[15896.511 15937.801 15952.315 15954.513 15960.002]]


 38%|███▊      | 141/370 [06:47<10:56,  2.87s/it]

[[288401.4  290269.38 290666.62 290690.88 290028.75]]


 38%|███▊      | 142/370 [06:50<10:45,  2.83s/it]

[[4344.32   4355.1772 4363.8765 4346.446  4248.627 ]]


 39%|███▊      | 143/370 [06:53<10:49,  2.86s/it]

[[462537.2  462645.28 461809.62 458980.47 457430.97]]


 39%|███▉      | 144/370 [06:55<10:42,  2.84s/it]

[[41466.406 41484.473 41579.996 41611.58  41544.535]]


 39%|███▉      | 145/370 [06:58<10:50,  2.89s/it]

[[56070.62  56102.113 56177.617 56470.867 56308.684]]


 39%|███▉      | 146/370 [07:01<10:39,  2.86s/it]

[[137472.69 136871.64 137069.48 135273.38 136550.16]]


 40%|███▉      | 147/370 [07:04<10:59,  2.96s/it]

[[74006.85  73682.25  73687.62  73771.7   73978.805]]


 40%|████      | 148/370 [07:07<10:46,  2.91s/it]

[[36972.984 37105.195 36763.625 36772.066 36694.13 ]]


 40%|████      | 149/370 [07:10<10:42,  2.91s/it]

[[80550.48  80132.88  80652.375 80927.055 80794.5  ]]


 41%|████      | 150/370 [07:13<10:33,  2.88s/it]

[[9868.599 9888.429 9879.857 9779.713 9713.17 ]]


 41%|████      | 151/370 [07:15<09:44,  2.67s/it]

[[ 99665.83   98406.15  100833.45  101699.05  101401.984]]


 41%|████      | 152/370 [07:18<09:37,  2.65s/it]

[[42928.535 43382.625 43241.938 42967.137 42376.902]]


 41%|████▏     | 153/370 [07:20<09:48,  2.71s/it]

[[179223.92 179654.22 179551.1  179618.67 176952.19]]


 42%|████▏     | 154/370 [07:24<10:24,  2.89s/it]

[[16193.529  16251.362  16064.193  15829.118  15764.5205]]


 42%|████▏     | 155/370 [07:27<10:26,  2.91s/it]

[[44118.008 43581.562 43590.996 44356.527 43975.652]]


 42%|████▏     | 156/370 [07:30<10:31,  2.95s/it]

[[10817.3955 10838.284  10807.025  10861.088  10863.395 ]]


 42%|████▏     | 157/370 [07:33<10:18,  2.90s/it]

[[122564.914 123243.65  124851.88  123816.89  124652.836]]


 43%|████▎     | 158/370 [07:35<09:31,  2.70s/it]

[[27781.076 27750.797 27870.643 27732.193 27893.992]]


 43%|████▎     | 159/370 [07:37<09:14,  2.63s/it]

[[84409.82  84528.63  84329.055 84782.414 84377.42 ]]


 43%|████▎     | 160/370 [07:40<09:22,  2.68s/it]

[[34532.65  34562.242 34154.168 34377.234 34315.047]]


 44%|████▎     | 161/370 [07:43<09:55,  2.85s/it]

[[5086.8853 5095.204  5112.8203 5113.4165 5079.6255]]


 44%|████▍     | 162/370 [07:46<09:34,  2.76s/it]

[[9468.469 9502.007 9613.799 9639.029 9555.178]]


 44%|████▍     | 163/370 [07:48<09:19,  2.70s/it]

[[90849.65  90652.84  90688.46  90634.305 90746.484]]


 44%|████▍     | 164/370 [07:51<09:09,  2.67s/it]

[[8445.591 8413.72  8474.056 8472.71  8435.333]]


 45%|████▍     | 165/370 [07:54<09:24,  2.75s/it]

[[26852.244 26808.648 26570.13  26599.375 26556.848]]


 45%|████▍     | 166/370 [07:57<09:22,  2.76s/it]

[[114016.36  113208.445 112878.61  112704.59  112146.89 ]]


 45%|████▌     | 167/370 [08:00<09:25,  2.79s/it]

[[13001.683 13020.446 12982.89  12990.21  13017.982]]


 45%|████▌     | 168/370 [08:03<09:55,  2.95s/it]

[[634698.5  634255.06 636009.8  637111.5  636082.6 ]]


 46%|████▌     | 169/370 [08:05<09:22,  2.80s/it]

[[5665.868  5661.9297 5672.052  5677.2803 5665.837 ]]


 46%|████▌     | 170/370 [08:08<09:04,  2.72s/it]

[[99330.78 99573.05 99922.74 99713.58 99913.91]]


 46%|████▌     | 171/370 [08:11<09:04,  2.74s/it]

[[103305.75 103299.14 103289.99 103292.85 103291.62]]


 46%|████▋     | 172/370 [08:13<09:01,  2.73s/it]

[[23720.37  23828.436 23828.625 23725.928 23689.926]]


 47%|████▋     | 173/370 [08:16<08:51,  2.70s/it]

[[150083.67 151236.86 151358.86 151298.36 150054.64]]


 47%|████▋     | 174/370 [08:18<08:30,  2.60s/it]

[[107561.87  107476.55  107528.26  107534.555 107530.34 ]]


 47%|████▋     | 175/370 [08:21<08:36,  2.65s/it]

[[17603.945 17690.893 17792.232 17802.8   17682.305]]


 48%|████▊     | 176/370 [08:24<09:11,  2.85s/it]

[[63667.625 63527.7   63565.547 63217.742 62463.46 ]]


 48%|████▊     | 177/370 [08:27<08:34,  2.66s/it]

[[25332.635 25194.09  25013.158 25035.312 25027.639]]


 48%|████▊     | 178/370 [08:29<08:16,  2.59s/it]

[[261261.55 265005.1  265600.6  267747.72 264137.3 ]]


 48%|████▊     | 179/370 [08:31<08:03,  2.53s/it]

[[12959.436  12945.1455 12938.897  12944.246  12939.672 ]]


 49%|████▊     | 180/370 [08:34<08:16,  2.61s/it]

[[657397.1  655841.2  654417.25 649114.75 651516.5 ]]


 49%|████▉     | 181/370 [08:37<08:02,  2.55s/it]

[[13774.605  13787.129  13732.213  13630.925  13597.6045]]


 49%|████▉     | 182/370 [08:39<08:01,  2.56s/it]

[[41190.215 41133.37  41101.566 41090.586 40765.66 ]]


 49%|████▉     | 183/370 [08:42<08:35,  2.75s/it]

[[138268.3  137449.77 138129.78 139131.48 139008.5 ]]


 50%|████▉     | 184/370 [08:45<08:47,  2.83s/it]

[[82847.14  82386.16  81776.016 81160.49  80530.98 ]]


 50%|█████     | 185/370 [08:48<08:32,  2.77s/it]

[[56768.902 57180.016 57331.84  56956.438 56001.67 ]]


 50%|█████     | 186/370 [08:51<08:12,  2.68s/it]

[[86865.01 85670.85 85692.09 84707.36 84985.99]]


 51%|█████     | 187/370 [08:53<07:45,  2.54s/it]

[[ 97372.64   97083.31   96994.766  99605.4   100106.21 ]]


 51%|█████     | 188/370 [08:55<07:33,  2.49s/it]

[[539176.3  537397.9  542127.6  541981.56 539550.3 ]]


 51%|█████     | 189/370 [08:58<07:48,  2.59s/it]

[[123481.516 123152.65  124151.4   124361.21  123648.81 ]]


 51%|█████▏    | 190/370 [09:01<08:01,  2.68s/it]

[[130216.664 128833.125 129889.38  129489.836 130617.73 ]]


 52%|█████▏    | 191/370 [09:04<08:08,  2.73s/it]

[[393205.78 391054.06 399063.88 405419.5  406221.03]]


 52%|█████▏    | 192/370 [09:07<08:14,  2.78s/it]

[[38308.562 38382.53  38365.67  38354.367 38284.52 ]]


 52%|█████▏    | 193/370 [09:09<08:03,  2.73s/it]

[[58278.44  56051.223 58231.105 60617.688 64742.105]]


 52%|█████▏    | 194/370 [09:12<08:17,  2.83s/it]

[[164910.02 165050.84 162464.48 151358.33 150633.45]]


 53%|█████▎    | 195/370 [09:15<08:04,  2.77s/it]

[[72406.1  72812.7  72501.69 71271.23 70248.99]]


 53%|█████▎    | 196/370 [09:18<08:04,  2.78s/it]

[[232393.44 229777.06 235591.36 233339.39 234353.55]]


 53%|█████▎    | 197/370 [09:21<08:19,  2.89s/it]

[[146382.78 146210.52 146219.86 146393.39 146572.27]]


 54%|█████▎    | 198/370 [09:24<08:05,  2.82s/it]

[[89665.84  90070.414 90322.31  90223.695 89926.34 ]]


 54%|█████▍    | 199/370 [09:26<08:01,  2.82s/it]

[[206951.1  202217.69 204267.45 199814.05 200620.69]]


 54%|█████▍    | 200/370 [09:29<07:35,  2.68s/it]

[[279745.   275878.25 275249.72 279340.8  277637.16]]


 54%|█████▍    | 201/370 [09:31<07:28,  2.65s/it]

[[42046.67  42334.926 42589.945 42579.363 42391.203]]


 55%|█████▍    | 202/370 [09:34<07:42,  2.75s/it]

[[138843.56 137426.34 133916.67 133300.84 136944.  ]]


 55%|█████▍    | 203/370 [09:37<07:19,  2.63s/it]

[[340889.   340809.8  341588.4  341983.75 342192.94]]


 55%|█████▌    | 204/370 [09:39<07:28,  2.70s/it]

[[40420.184 40302.684 41413.94  41541.04  40520.875]]


 55%|█████▌    | 205/370 [09:43<07:55,  2.88s/it]

[[61244.523 61052.562 61260.71  61297.13  61096.332]]


 56%|█████▌    | 206/370 [09:45<07:37,  2.79s/it]

[[112688.79 112652.24 112487.47 111260.19 112380.49]]


 56%|█████▌    | 207/370 [09:48<07:17,  2.68s/it]

[[ 97867.1   93484.89  93610.35  93759.82 100998.97]]


 56%|█████▌    | 208/370 [09:51<07:20,  2.72s/it]

[[17774.23  17658.06  17415.463 17649.291 17798.64 ]]


 56%|█████▋    | 209/370 [09:53<07:14,  2.70s/it]

[[19568.873 19716.1   19825.885 20086.488 20025.521]]


 57%|█████▋    | 210/370 [09:56<07:14,  2.72s/it]

[[115750.16 114430.   114899.25 117150.81 114350.51]]


 57%|█████▋    | 211/370 [09:59<07:13,  2.72s/it]

[[51747.977 51857.85  52429.46  51744.004 53036.38 ]]


 57%|█████▋    | 212/370 [10:02<07:39,  2.91s/it]

[[15231.13   15327.2295 15270.678  15146.467  14918.465 ]]


 58%|█████▊    | 213/370 [10:05<07:42,  2.95s/it]

[[37960.383 38233.48  38304.418 38265.33  37701.805]]


 58%|█████▊    | 214/370 [10:08<07:32,  2.90s/it]

[[105307.66  103267.555 105012.2   103516.805 105443.44 ]]


 58%|█████▊    | 215/370 [10:11<07:33,  2.92s/it]

[[208900.08 208336.3  208844.6  208748.89 208382.48]]


 58%|█████▊    | 216/370 [10:14<07:23,  2.88s/it]

[[157842.92 156672.36 157333.97 156647.47 158451.73]]


 59%|█████▊    | 217/370 [10:17<07:28,  2.93s/it]

[[19062.316 19060.717 19071.395 18969.402 18913.572]]


 59%|█████▉    | 218/370 [10:20<07:21,  2.91s/it]

[[36667.273 36599.375 36500.348 36964.656 36545.113]]


 59%|█████▉    | 219/370 [10:23<07:23,  2.94s/it]

[[45669.074 45821.125 45742.605 44960.63  45223.504]]


 59%|█████▉    | 220/370 [10:25<07:16,  2.91s/it]

[[72551.26  71917.    72533.914 72797.95  71373.69 ]]


 60%|█████▉    | 221/370 [10:28<07:08,  2.88s/it]

[[19033.492 19028.602 19054.389 19051.105 18772.38 ]]


 60%|██████    | 222/370 [10:31<07:03,  2.86s/it]

[[48231.594 48089.52  48063.4   48273.125 48239.797]]


 60%|██████    | 223/370 [10:34<06:47,  2.77s/it]

[[18258.22  18282.242 18204.945 18044.55  18051.783]]


 61%|██████    | 224/370 [10:36<06:36,  2.72s/it]

[[33819.086 33833.1   33817.64  34225.902 34044.13 ]]


 61%|██████    | 225/370 [10:39<06:50,  2.83s/it]

[[110619.01  110685.38  110578.51  109986.28  109069.375]]


 61%|██████    | 226/370 [10:42<06:59,  2.91s/it]

[[61903.297 61844.12  61781.746 60439.06  59025.316]]


 61%|██████▏   | 227/370 [10:45<06:56,  2.91s/it]

[[49334.07  49237.78  48875.727 48582.332 48921.746]]


 62%|██████▏   | 228/370 [10:48<06:52,  2.90s/it]

[[37898.824 37875.844 38189.16  37216.926 36178.715]]


 62%|██████▏   | 229/370 [10:51<06:45,  2.88s/it]

[[145074.14 144097.64 143454.47 143538.06 143588.25]]


 62%|██████▏   | 230/370 [10:53<06:25,  2.76s/it]

[[34088.664 34537.17  34175.023 33538.254 34121.715]]


 62%|██████▏   | 231/370 [10:56<06:01,  2.60s/it]

[[57332.113 56731.426 57060.11  56473.215 56227.293]]


 63%|██████▎   | 232/370 [10:58<05:50,  2.54s/it]

[[57164.094 57689.484 57562.953 57081.902 57049.215]]


 63%|██████▎   | 233/370 [11:01<06:01,  2.64s/it]

[[6403.895  6424.9453 6416.0933 6409.038  6387.589 ]]


 63%|██████▎   | 234/370 [11:04<06:16,  2.77s/it]

[[190003.14 190474.3  190720.75 190666.83 190343.17]]


 64%|██████▎   | 235/370 [11:07<06:16,  2.79s/it]

[[7287.7524 7294.281  7122.1777 7071.4395 6917.2603]]


 64%|██████▍   | 236/370 [11:10<06:18,  2.83s/it]

[[45034.56  44970.684 45095.56  44957.363 44930.996]]


 64%|██████▍   | 237/370 [11:13<06:21,  2.87s/it]

[[20194.785 20351.535 20139.088 20073.686 20415.22 ]]


 64%|██████▍   | 238/370 [11:16<06:13,  2.83s/it]

[[20766.805 20790.014 20706.064 20592.781 20488.81 ]]


 65%|██████▍   | 239/370 [11:18<05:55,  2.71s/it]

[[44429.395 44479.91  44380.133 44284.117 43985.086]]


 65%|██████▍   | 240/370 [11:21<05:53,  2.72s/it]

[[15379.147 15420.852 15368.12  15250.478 15161.079]]


 65%|██████▌   | 241/370 [11:24<06:15,  2.91s/it]

[[53401.797 52669.18  52574.69  51812.344 50808.523]]


 65%|██████▌   | 242/370 [11:27<06:00,  2.81s/it]

[[15838.244 15809.286 15775.57  15613.484 15578.837]]


 66%|██████▌   | 243/370 [11:29<05:54,  2.79s/it]

[[25942.795 25911.393 25864.045 25759.793 25734.566]]


 66%|██████▌   | 244/370 [11:32<05:34,  2.66s/it]

[[53354.285 53099.137 53260.566 53210.42  53435.59 ]]


 66%|██████▌   | 245/370 [11:34<05:34,  2.68s/it]

[[29518.334 29519.72  29449.729 28954.936 28650.582]]


 66%|██████▋   | 246/370 [11:37<05:22,  2.60s/it]

[[61483.418 61745.57  61849.46  61664.574 61328.773]]


 67%|██████▋   | 247/370 [11:39<05:15,  2.56s/it]

[[98079.25  97577.87  96975.44  96420.4   96511.414]]


 67%|██████▋   | 248/370 [11:42<05:29,  2.70s/it]

[[61724.57  61717.355 62002.223 61646.344 60834.992]]


 67%|██████▋   | 249/370 [11:45<05:19,  2.64s/it]

[[32239.156 32115.354 32417.613 31959.61  32026.44 ]]


 68%|██████▊   | 250/370 [11:47<05:15,  2.63s/it]

[[12890.908 12796.687 12815.124 12848.057 12891.041]]


 68%|██████▊   | 251/370 [11:50<05:16,  2.66s/it]

[[210817.66 211318.72 210326.31 209673.16 210502.22]]


 68%|██████▊   | 252/370 [11:53<05:09,  2.62s/it]

[[75404.805 75244.07  75408.47  75542.18  75376.73 ]]


 68%|██████▊   | 253/370 [11:55<05:10,  2.66s/it]

[[22877.516 22798.447 22704.727 22698.568 22917.637]]


 69%|██████▊   | 254/370 [11:58<04:59,  2.58s/it]

[[20695.814 20628.418 20668.627 20624.41  20614.56 ]]


 69%|██████▉   | 255/370 [12:01<05:12,  2.72s/it]

[[6503.48   6485.37   6523.904  6504.363  6559.0747]]


 69%|██████▉   | 256/370 [12:03<05:03,  2.66s/it]

[[110273.06  109627.89  110033.84  110710.29  109876.984]]


 69%|██████▉   | 257/370 [12:06<05:03,  2.69s/it]

[[10456.077  10450.584  10465.524  10460.957  10276.0625]]


 70%|██████▉   | 258/370 [12:09<05:04,  2.72s/it]

[[45378.457 44837.215 46582.17  48351.82  48318.605]]


 70%|███████   | 259/370 [12:11<04:50,  2.62s/it]

[[10482.573 10419.198 10371.752 10207.09  10135.691]]


 70%|███████   | 260/370 [12:14<04:50,  2.65s/it]

[[177098.47 176788.08 181092.52 177880.45 175838.27]]


 71%|███████   | 261/370 [12:17<04:53,  2.70s/it]

[[35439.426 35799.95  35531.12  35035.242 34588.434]]


 71%|███████   | 262/370 [12:20<05:07,  2.85s/it]

[[113359.51  111385.73  114453.04  117221.555 121594.66 ]]


 71%|███████   | 263/370 [12:23<04:57,  2.78s/it]

[[27928.432 27611.525 27099.016 27060.615 27357.414]]


 71%|███████▏  | 264/370 [12:25<04:48,  2.73s/it]

[[60556.29  60593.117 60838.33  60792.176 60768.36 ]]


 72%|███████▏  | 265/370 [12:28<04:40,  2.67s/it]

[[77559.51  77790.76  77940.805 78493.18  78383.53 ]]


 72%|███████▏  | 266/370 [12:30<04:31,  2.61s/it]

[[146869.33 145540.42 143411.69 141143.44 141367.31]]


 72%|███████▏  | 267/370 [12:33<04:21,  2.54s/it]

[[18406.021 18289.178 18376.006 18273.738 18328.809]]


 72%|███████▏  | 268/370 [12:35<04:17,  2.53s/it]

[[4326.561  4330.57   4313.847  4296.5205 4141.031 ]]


 73%|███████▎  | 269/370 [12:38<04:18,  2.56s/it]

[[40878.65  40946.19  41132.453 41130.05  41124.09 ]]


 73%|███████▎  | 270/370 [12:41<04:36,  2.76s/it]

[[17088.27  17068.146 17063.506 17025.018 17025.402]]


 73%|███████▎  | 271/370 [12:44<04:29,  2.72s/it]

[[61962.613 61382.586 59758.953 58035.562 57588.055]]


 74%|███████▎  | 272/370 [12:47<04:32,  2.78s/it]

[[15289.716 15375.643 15427.239 15404.578 15393.86 ]]


 74%|███████▍  | 273/370 [12:49<04:30,  2.79s/it]

[[28685.14  28741.928 28818.977 28604.955 28897.162]]


 74%|███████▍  | 274/370 [12:52<04:09,  2.60s/it]

[[39492.195 39166.047 39354.14  39227.383 41213.24 ]]


 74%|███████▍  | 275/370 [12:54<04:06,  2.60s/it]

[[18595.123 18374.463 18312.85  18520.604 18448.73 ]]


 75%|███████▍  | 276/370 [12:57<03:58,  2.53s/it]

[[43101.41  43027.31  42923.875 42950.375 42903.09 ]]


 75%|███████▍  | 277/370 [13:00<04:15,  2.75s/it]

[[39995.84  39392.1   38992.23  39414.742 39938.418]]


 75%|███████▌  | 278/370 [13:03<04:13,  2.75s/it]

[[40288.32  39903.996 39875.156 40586.99  41031.16 ]]


 75%|███████▌  | 279/370 [13:05<04:05,  2.70s/it]

[[15605.977 15878.382 15795.563 15667.94  15652.186]]


 76%|███████▌  | 280/370 [13:08<03:58,  2.66s/it]

[[29734.293 29524.209 29667.51  29731.81  29705.283]]


 76%|███████▌  | 281/370 [13:10<03:54,  2.63s/it]

[[48933.215 48828.2   48069.457 46303.31  45283.93 ]]


 76%|███████▌  | 282/370 [13:13<03:49,  2.60s/it]

[[21938.607 21792.797 22067.146 22454.717 22820.438]]


 76%|███████▋  | 283/370 [13:16<03:55,  2.70s/it]

[[34709.99  34906.277 34862.09  34682.812 34236.86 ]]


 77%|███████▋  | 284/370 [13:19<03:58,  2.77s/it]

[[33693.082 33611.246 33715.426 33790.684 33738.6  ]]


 77%|███████▋  | 285/370 [13:22<04:02,  2.85s/it]

[[8316.367 8228.641 8181.88  8174.245 8492.978]]


 77%|███████▋  | 286/370 [13:24<03:46,  2.70s/it]

[[55892.793 56314.547 57188.434 58213.066 57725.72 ]]


 78%|███████▊  | 287/370 [13:26<03:35,  2.59s/it]

[[67298.85  67339.84  67245.9   67192.75  67020.625]]


 78%|███████▊  | 288/370 [13:29<03:27,  2.53s/it]

[[40982.72  41250.91  41543.38  41257.336 41422.67 ]]


 78%|███████▊  | 289/370 [13:31<03:26,  2.55s/it]

[[56259.9   55763.734 55147.8   55975.086 56176.855]]


 78%|███████▊  | 290/370 [13:34<03:29,  2.62s/it]

[[5715.794  5749.471  5735.782  5771.588  5717.4194]]


 79%|███████▊  | 291/370 [13:37<03:41,  2.81s/it]

[[16294.387 16283.871 16498.678 16478.986 16537.496]]


 79%|███████▉  | 292/370 [13:40<03:34,  2.75s/it]

[[35877.94  36269.875 36254.164 36329.027 36030.117]]


 79%|███████▉  | 293/370 [13:42<03:18,  2.58s/it]

[[50773.664 50742.34  50733.984 50708.723 50729.598]]


 79%|███████▉  | 294/370 [13:45<03:20,  2.64s/it]

[[70199.29 70493.27 70206.44 70036.43 69662.47]]


 80%|███████▉  | 295/370 [13:47<03:12,  2.56s/it]

[[18708.018 18822.77  18923.842 19103.158 18964.762]]


 80%|████████  | 296/370 [13:50<03:18,  2.68s/it]

[[4118.6533 4125.051  4119.959  4115.4575 4115.5825]]


 80%|████████  | 297/370 [13:53<03:13,  2.64s/it]

[[16566.242 16205.163 16471.205 17113.287 17583.713]]


 81%|████████  | 298/370 [13:56<03:12,  2.67s/it]

[[3557.9722 3544.5544 3539.6995 3527.29   3465.9998]]


 81%|████████  | 299/370 [13:58<03:13,  2.72s/it]

[[48812.094 48881.188 48738.51  48758.215 48798.402]]


 81%|████████  | 300/370 [14:01<03:07,  2.68s/it]

[[40941.387 42328.688 41760.574 42476.28  42691.246]]


 81%|████████▏ | 301/370 [14:03<02:59,  2.60s/it]

[[15076.11  15059.388 15087.264 15106.765 15116.625]]


 82%|████████▏ | 302/370 [14:06<03:03,  2.70s/it]

[[28900.52  28956.812 29189.158 29135.451 28713.518]]


 82%|████████▏ | 303/370 [14:09<03:01,  2.71s/it]

[[20633.77  20555.357 20351.621 20403.178 20568.238]]


 82%|████████▏ | 304/370 [14:12<02:56,  2.68s/it]

[[76647.695 77327.96  76496.24  74573.76  73645.55 ]]


 82%|████████▏ | 305/370 [14:14<02:52,  2.65s/it]

[[5002.431  5031.904  5089.536  5061.3223 5110.24  ]]


 83%|████████▎ | 306/370 [14:18<03:00,  2.83s/it]

[[7933.44   7926.9023 7927.292  7880.044  7848.257 ]]


 83%|████████▎ | 307/370 [14:20<02:51,  2.72s/it]

[[7318.664  7320.2334 7263.315  7315.9287 7283.86  ]]


 83%|████████▎ | 308/370 [14:23<02:50,  2.75s/it]

[[ 9825.487  9633.142  9690.47   9870.675 10197.062]]


 84%|████████▎ | 309/370 [14:25<02:40,  2.64s/it]

[[39716.863 39713.473 39887.35  39722.938 39794.484]]


 84%|████████▍ | 310/370 [14:27<02:29,  2.49s/it]

[[13581.833 13390.763 13303.644 13461.467 14071.015]]


 84%|████████▍ | 311/370 [14:30<02:28,  2.51s/it]

[[20047.297 20065.715 20027.188 19904.713 19883.46 ]]


 84%|████████▍ | 312/370 [14:32<02:22,  2.46s/it]

[[48296.535 49057.395 49401.703 49428.13  48733.51 ]]


 85%|████████▍ | 313/370 [14:35<02:25,  2.55s/it]

[[17280.598 17280.178 17303.25  17261.14  17284.756]]


 85%|████████▍ | 314/370 [14:38<02:32,  2.73s/it]

[[4742.2183 4769.476  4776.6816 4785.003  4767.3228]]


 85%|████████▌ | 315/370 [14:41<02:24,  2.63s/it]

[[25656.781 25753.902 25810.287 25650.607 25465.725]]


 85%|████████▌ | 316/370 [14:44<02:28,  2.74s/it]

[[28941.113 29600.412 30223.17  30429.27  30359.52 ]]


 86%|████████▌ | 317/370 [14:46<02:25,  2.75s/it]

[[14930.775  15059.775  15063.961  14952.178  15147.8545]]


 86%|████████▌ | 318/370 [14:49<02:16,  2.63s/it]

[[69270.266 69395.48  69362.56  69365.59  68759.36 ]]


 86%|████████▌ | 319/370 [14:51<02:15,  2.66s/it]

[[46065.816 45981.72  46341.53  46508.383 46469.926]]


 86%|████████▋ | 320/370 [14:54<02:12,  2.64s/it]

[[30970.17  30824.047 30823.48  30820.127 30847.102]]


 87%|████████▋ | 321/370 [14:57<02:13,  2.72s/it]

[[24130.6   24070.41  24059.434 24047.248 23939.32 ]]


 87%|████████▋ | 322/370 [15:00<02:11,  2.75s/it]

[[5153.389  5193.476  5194.785  5130.438  5090.7725]]


 87%|████████▋ | 323/370 [15:03<02:09,  2.75s/it]

[[27928.145 27782.424 27563.857 27386.582 27262.182]]


 88%|████████▊ | 324/370 [15:05<02:07,  2.77s/it]

[[11542.911 11555.19  11457.7   11359.622 11189.851]]


 88%|████████▊ | 325/370 [15:08<02:02,  2.72s/it]

[[13019.933 13093.161 13055.168 12985.09  12899.917]]


 88%|████████▊ | 326/370 [15:11<02:02,  2.78s/it]

[[28287.398 28482.662 28453.027 28397.307 28324.732]]


 88%|████████▊ | 327/370 [15:13<01:55,  2.68s/it]

[[17879.793 17827.52  17814.445 17817.56  17714.717]]


 89%|████████▊ | 328/370 [15:17<01:59,  2.84s/it]

[[24980.873 25020.924 24910.107 24744.178 24124.582]]


 89%|████████▉ | 329/370 [15:19<01:51,  2.73s/it]

[[52994.99  53099.87  52636.12  52386.566 51823.434]]


 89%|████████▉ | 330/370 [15:21<01:42,  2.57s/it]

[[45823.887 45744.934 46298.77  46160.855 46159.934]]


 89%|████████▉ | 331/370 [15:24<01:38,  2.54s/it]

[[40113.977 40004.34  40071.105 40074.48  39958.4  ]]


 90%|████████▉ | 332/370 [15:26<01:37,  2.56s/it]

[[39200.24  39427.71  39501.2   39340.97  39227.188]]


 90%|█████████ | 333/370 [15:29<01:37,  2.62s/it]

[[11166.054 11110.45  11114.794 11115.672 11118.513]]


 90%|█████████ | 334/370 [15:32<01:35,  2.66s/it]

[[13466.895 13479.943 13593.47  13571.568 13339.928]]


 91%|█████████ | 335/370 [15:34<01:32,  2.65s/it]

[[7240.643  7172.8164 7118.351  7181.14   7129.3447]]


 91%|█████████ | 336/370 [15:37<01:34,  2.77s/it]

[[14666.19   14660.305  14760.1455 14651.327  14786.034 ]]


 91%|█████████ | 337/370 [15:40<01:31,  2.77s/it]

[[8216.262  8006.5044 8014.1533 7824.2295 8472.953 ]]


 91%|█████████▏| 338/370 [15:42<01:22,  2.59s/it]

[[18920.988 19022.35  19061.496 19038.156 19036.521]]


 92%|█████████▏| 339/370 [15:45<01:16,  2.45s/it]

[[36969.508 37004.543 37393.08  37860.406 38143.953]]


 92%|█████████▏| 340/370 [15:47<01:16,  2.55s/it]

[[42042.152 41988.582 42025.28  42130.543 42165.773]]


 92%|█████████▏| 341/370 [15:50<01:12,  2.51s/it]

[[47362.457 47325.098 47332.957 47335.055 47437.086]]


 92%|█████████▏| 342/370 [15:52<01:11,  2.54s/it]

[[8939.312 9020.202 9028.643 8997.874 8888.072]]


 93%|█████████▎| 343/370 [15:55<01:12,  2.67s/it]

[[15699.531  15601.27   15843.3955 15961.154  16253.8125]]


 93%|█████████▎| 344/370 [15:58<01:10,  2.71s/it]

[[5897.6045 5921.5757 5904.74   5889.3315 5760.9595]]


 93%|█████████▎| 345/370 [16:01<01:08,  2.73s/it]

[[25347.9   25306.938 25204.863 25121.281 24497.234]]


 94%|█████████▎| 346/370 [16:04<01:05,  2.73s/it]

[[35869.34  35848.74  36025.234 36190.984 36061.344]]


 94%|█████████▍| 347/370 [16:06<01:03,  2.74s/it]

[[9016.039 9041.813 9051.159 9027.601 8961.153]]


 94%|█████████▍| 348/370 [16:09<00:59,  2.71s/it]

[[22355.633 22500.47  22398.727 22274.354 21576.566]]


 94%|█████████▍| 349/370 [16:11<00:53,  2.56s/it]

[[20987.176 20971.762 20942.738 20779.326 20469.39 ]]


 95%|█████████▍| 350/370 [16:14<00:51,  2.57s/it]

[[3007.8022 3011.6792 3015.1318 3015.3682 3000.7688]]


 95%|█████████▍| 351/370 [16:16<00:47,  2.52s/it]

[[6352.3823 6324.7207 6298.1235 6200.2466 6179.8887]]


 95%|█████████▌| 352/370 [16:19<00:46,  2.59s/it]

[[6920.094  6917.5063 6914.689  6910.104  6912.1387]]


 95%|█████████▌| 353/370 [16:21<00:42,  2.52s/it]

[[53321.312 53301.39  53573.418 53764.684 53539.824]]


 96%|█████████▌| 354/370 [16:24<00:41,  2.60s/it]

[[23197.984 23200.436 23204.398 23174.814 23137.006]]


 96%|█████████▌| 355/370 [16:27<00:41,  2.77s/it]

[[22965.06  23238.34  23198.486 23429.967 23252.496]]


 96%|█████████▌| 356/370 [16:30<00:38,  2.75s/it]

[[7889.57   7888.4927 7891.1294 7959.9395 8025.4194]]


 96%|█████████▋| 357/370 [16:33<00:37,  2.89s/it]

[[38550.438 38550.383 38550.33  38550.316 38550.336]]


 97%|█████████▋| 358/370 [16:36<00:33,  2.79s/it]

[[25357.58  25017.123 25152.105 25744.033 26936.81 ]]


 97%|█████████▋| 359/370 [16:39<00:30,  2.79s/it]

[[10831.295 10850.242 10947.417 11100.965 10951.618]]


 97%|█████████▋| 360/370 [16:41<00:27,  2.78s/it]

[[30453.094 30524.412 30508.156 30501.041 30290.572]]


 98%|█████████▊| 361/370 [16:44<00:24,  2.76s/it]

[[8643.903 8646.52  8647.358 8649.085 8645.303]]


 98%|█████████▊| 362/370 [16:47<00:21,  2.73s/it]

[[31426.14  31785.443 31570.664 31626.74  31304.227]]


 98%|█████████▊| 363/370 [16:49<00:18,  2.60s/it]

[[36823.984 36828.89  36798.555 36832.168 36804.973]]


 98%|█████████▊| 364/370 [16:52<00:17,  2.85s/it]

[[1700.7014 1712.2258 1702.7924 1702.9949 1695.0526]]


 99%|█████████▊| 365/370 [16:55<00:14,  2.85s/it]

[[7855.832  7885.9077 7927.918  7849.8496 7953.9395]]


 99%|█████████▉| 366/370 [16:58<00:11,  2.77s/it]

[[4570.199  4559.0215 4563.139  4569.6826 4585.551 ]]


 99%|█████████▉| 367/370 [17:01<00:08,  2.77s/it]

[[14093.074  13378.72   13506.711  14130.3545 14580.372 ]]


 99%|█████████▉| 368/370 [17:03<00:05,  2.65s/it]

[[6444.4204 6439.068  6430.8916 6392.249  6323.882 ]]


100%|█████████▉| 369/370 [17:06<00:02,  2.65s/it]

[[46510.504 48066.08  47901.566 47753.082 47761.832]]


100%|██████████| 370/370 [17:08<00:00,  2.78s/it]

[[47254.63  47088.348 47063.31  46841.965 46328.574]]


In [20]:
submission.isna().sum().sum()

0

In [21]:
submission

Day        000060  ...        363280        950130
0  2021-11-01  29059.160156  ...  26431.703125  17880.105469
1  2021-11-02  29288.392578  ...  26702.648438  17867.044922
2  2021-11-03  29443.205078  ...  26779.953125  17888.453125
3  2021-11-04  29353.425781  ...  26692.367188  17784.464844
4  2021-11-05  28742.460938  ...  26559.785156  17670.412109
5  2021-11-29  29696.865234  ...  25332.634766  15838.244141
6  2021-11-30  29541.376953  ...  25194.089844  15809.286133
7  2021-12-01  30274.095703  ...  25013.158203  15775.570312
8  2021-12-02  30746.892578  ...  25035.312500  15613.484375
9  2021-12-03  30904.554688  ...  25027.638672  15578.836914

[10 rows x 371 columns]

In [22]:
submission.to_csv("/content/drive/MyDrive/주식 종가 예측/submission_simpleRNN_ver3.csv", index = False)